# Generated by Django 4.2.7 on 2023-11-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description1', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
