# Generated by Django 4.2.7 on 2023-11-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chairs_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameChairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description1', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeChairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description1', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrtChairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description1', models.CharField(max_length=200)),
                ('description2', models.CharField(max_length=200)),
            ],
        ),
    ]
