# Generated by Django 4.2.7 on 2023-11-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gamechairs_officechairs_ortchairs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chairs',
        ),
        migrations.AlterField(
            model_name='gamechairs',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='officechairs',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ortchairs',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
