# Generated by Django 4.2.7 on 2023-11-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_officechairs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamechairs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/content/products/chairs/gameChairs/preview/'),
        ),
        migrations.AddField(
            model_name='ortchairs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/content/products/chairs/ortChairs/preview/'),
        ),
    ]
