# Generated by Django 4.2.7 on 2023-12-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_gamechairs_image_ortchairs_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_DirChairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/content/main/')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='images/content/main/dirChairs/left')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='images/content/main/dirChairs/right')),
            ],
        ),
        migrations.CreateModel(
            name='Main_GameChairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/content/main/')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='images/content/main/gameChairs/left')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='images/content/main/gameChairs/right')),
            ],
        ),
        migrations.CreateModel(
            name='Main_OfficeChairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/content/main/')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='images/content/main/officeChairs/right')),
            ],
        ),
        migrations.CreateModel(
            name='Main_OrtChairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/content/main/')),
                ('image_left', models.ImageField(blank=True, null=True, upload_to='images/content/main/ortChairs/left')),
                ('image_right', models.ImageField(blank=True, null=True, upload_to='images/content/main/ortChairs/right')),
            ],
        ),
    ]
